package com.uptrail.claim.service;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.HexFormat;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

import com.uptrail.claim.service.DocumentTypeDetector.Format;
import com.uptrail.shared.time.BusinessClock;

/**
 * Private file store for claim documents. Files live outside the web root under keys generated by the server
 * ({@code yyyy/MM/<uuid>.<ext>}); a request never chooses a path. A file written inside a transaction is
 * deleted again when that transaction rolls back, and a periodic sweep removes files that no database row
 * references (for example after a crash between writing the file and committing).
 */
@Component
public class DocumentStorage {

    /** A received file before validation. */
    public record Upload(String originalName, byte[] content) {

        public boolean isEmpty() {
            return content == null || content.length == 0;
        }
    }

    /** A validated file ready to be written. */
    public record Prepared(String originalName, Format format, byte[] content, String sha256) {

        public long size() {
            return content.length;
        }
    }

    private static final Logger log = LoggerFactory.getLogger(DocumentStorage.class);
    private static final Pattern KEY = Pattern.compile("\\d{4}/\\d{2}/[0-9a-f-]{36}\\.(pdf|png|jpg)");
    private static final DateTimeFormatter FOLDER = DateTimeFormatter.ofPattern("yyyy/MM").withZone(ZoneOffset.UTC);
    private static final String TEMP_DIR = ".incoming";
    private static final int MAX_NAME = 200;

    private final Path root;
    private final long maxBytes;
    private final BusinessClock clock;

    public DocumentStorage(@Value("${uptrail.documents.root}") String root,
            @Value("${uptrail.documents.max-bytes}") long maxBytes, BusinessClock clock) {
        this.root = Path.of(root).toAbsolutePath().normalize();
        this.maxBytes = maxBytes;
        this.clock = clock;
    }

    public long maxBytes() {
        return maxBytes;
    }

    /**
     * Checks size and format and computes the checksum. Returns the problem as text so that the caller can
     * report every missing or unacceptable file at once.
     */
    public Result prepare(Upload upload) {
        if (upload == null || upload.isEmpty()) {
            return Result.problem("Attach the file.");
        }
        if (upload.content().length > maxBytes) {
            return Result.problem("The file is larger than " + (maxBytes / (1024 * 1024)) + " MB.");
        }
        String name = displayName(upload.originalName());
        Optional<Format> format = DocumentTypeDetector.detect(name, upload.content());
        if (format.isEmpty()) {
            return Result.problem("The file is not a PDF, PNG or JPEG document, or its name does not end in "
                    + ".pdf, .png, .jpg or .jpeg.");
        }
        return Result.ok(new Prepared(name, format.get(), upload.content(), sha256(upload.content())));
    }

    public record Result(Prepared prepared, String problem) {

        static Result ok(Prepared prepared) {
            return new Result(prepared, null);
        }

        static Result problem(String problem) {
            return new Result(null, problem);
        }

        public boolean isOk() {
            return prepared != null;
        }
    }

    /**
     * Writes the file and returns its storage key. Must run inside a transaction: the file is removed again
     * if the transaction does not commit.
     */
    public String save(Prepared prepared) {
        if (!TransactionSynchronizationManager.isSynchronizationActive()) {
            throw new IllegalStateException("Documents are saved inside the business transaction");
        }
        String key = FOLDER.format(clock.now()) + "/" + UUID.randomUUID() + "." + prepared.format().extension();
        Path target = resolve(key);
        try {
            Path incoming = root.resolve(TEMP_DIR);
            Files.createDirectories(incoming);
            Files.createDirectories(target.getParent());
            Path temp = incoming.resolve(UUID.randomUUID() + ".part");
            Files.write(temp, prepared.content(), StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
            Files.move(temp, target, StandardCopyOption.ATOMIC_MOVE);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not store a claim document", e);
        }
        TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
            @Override
            public void afterCompletion(int status) {
                if (status != STATUS_COMMITTED) {
                    deleteQuietly(target);
                }
            }
        });
        return key;
    }

    public Path open(String key) {
        Path path = resolve(key);
        if (!Files.isRegularFile(path)) {
            throw new IllegalStateException("A stored claim document is missing: " + key);
        }
        return path;
    }

    public boolean exists(String key) {
        return Files.isRegularFile(resolve(key));
    }

    /**
     * Deletes stored files that are older than {@code minimumAge} and not in {@code knownKeys}. The age limit
     * leaves files of transactions that are still running alone.
     */
    public int sweepOrphans(Set<String> knownKeys, Duration minimumAge) {
        if (!Files.isDirectory(root)) {
            return 0;
        }
        // File ages come from the file system, so they are compared with the system time, not the business clock.
        Instant cutoff = Instant.now().minus(minimumAge);
        int removed = 0;
        try (Stream<Path> files = Files.walk(root)) {
            for (Path file : (Iterable<Path>) files.filter(Files::isRegularFile)::iterator) {
                String key = root.relativize(file).toString().replace('\\', '/');
                boolean temporary = key.startsWith(TEMP_DIR + "/");
                if ((temporary || !knownKeys.contains(key)) && Files.getLastModifiedTime(file).toInstant().isBefore(cutoff)) {
                    deleteQuietly(file);
                    removed++;
                }
            }
        } catch (IOException e) {
            throw new UncheckedIOException("Could not sweep the document directory", e);
        }
        removeEmptyFolders();
        return removed;
    }

    private void removeEmptyFolders() {
        try (Stream<Path> dirs = Files.walk(root)) {
            dirs.filter(Files::isDirectory).filter(dir -> !dir.equals(root))
                    .sorted((a, b) -> b.getNameCount() - a.getNameCount())
                    .forEach(dir -> {
                        try (DirectoryStream<Path> entries = Files.newDirectoryStream(dir)) {
                            if (!entries.iterator().hasNext()) {
                                Files.delete(dir);
                            }
                        } catch (IOException ignored) {
                            // A folder that cannot be removed now is tried again by the next sweep.
                        }
                    });
        } catch (IOException ignored) {
            // Folder clean-up is cosmetic.
        }
    }

    private Path resolve(String key) {
        if (key == null || !KEY.matcher(key).matches()) {
            throw new IllegalArgumentException("Invalid document key");
        }
        Path path = root.resolve(key).normalize();
        if (!path.startsWith(root)) {
            throw new IllegalArgumentException("Invalid document key");
        }
        return path;
    }

    private static void deleteQuietly(Path file) {
        try {
            Files.deleteIfExists(file);
        } catch (IOException e) {
            log.warn("Could not delete document file {}; the orphan sweep will retry", file.getFileName());
        }
    }

    /** The last path segment of the browser-supplied name without control characters, for display only. */
    static String displayName(String originalName) {
        String name = originalName == null ? "" : originalName;
        name = name.substring(Math.max(name.lastIndexOf('/'), name.lastIndexOf('\\')) + 1);
        name = name.replaceAll("\\p{Cntrl}", "").strip();
        if (name.isEmpty() || name.equals(".") || name.equals("..")) {
            name = "document";
        }
        if (name.length() > MAX_NAME) {
            String extension = DocumentTypeDetector.extensionOf(name);
            String suffix = extension.isEmpty() ? "" : "." + extension;
            name = name.substring(0, MAX_NAME - suffix.length()) + suffix;
        }
        return name;
    }

    private static String sha256(byte[] content) {
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(content));
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }
}
