package com.uptrail.claim.domain;

import java.time.Instant;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Metadata of a receipt or certificate stored in the private document directory. The storage key is
 * generated by the server; request data never chooses a path.
 */
@Entity
@Immutable
@Table(name = "claim_document")
public class ClaimDocument {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "claim_id", nullable = false)
    private Long claimId;

    @Column(name = "claim_revision", nullable = false)
    private int claimRevision;

    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Column(name = "document_type", nullable = false, length = 24)
    private DocumentType documentType;

    @Column(name = "storage_key", nullable = false, length = 200)
    private String storageKey;

    @Column(name = "original_name", nullable = false, length = 200)
    private String originalName;

    @Column(name = "detected_content_type", nullable = false, length = 100)
    private String detectedContentType;

    @Column(name = "size_bytes", nullable = false)
    private long sizeBytes;

    @Column(name = "sha256", nullable = false, length = 64)
    private String sha256;

    @Column(name = "uploaded_by", nullable = false)
    private Long uploadedBy;

    @Column(name = "uploaded_at", nullable = false)
    private Instant uploadedAt;

    protected ClaimDocument() {
    }

    public static ClaimDocument record(Long claimId, int claimRevision, DocumentType type, String storageKey,
            String originalName, String contentType, long sizeBytes, String sha256, Long uploadedBy, Instant now) {
        ClaimDocument document = new ClaimDocument();
        document.claimId = Objects.requireNonNull(claimId);
        document.claimRevision = claimRevision;
        document.documentType = Objects.requireNonNull(type);
        document.storageKey = Objects.requireNonNull(storageKey);
        document.originalName = Objects.requireNonNull(originalName);
        document.detectedContentType = Objects.requireNonNull(contentType);
        document.sizeBytes = sizeBytes;
        document.sha256 = Objects.requireNonNull(sha256);
        document.uploadedBy = Objects.requireNonNull(uploadedBy);
        document.uploadedAt = now;
        return document;
    }

    public Long getId() {
        return id;
    }

    public Long getClaimId() {
        return claimId;
    }

    public int getClaimRevision() {
        return claimRevision;
    }

    public DocumentType getDocumentType() {
        return documentType;
    }

    public String getStorageKey() {
        return storageKey;
    }

    public String getOriginalName() {
        return originalName;
    }

    public String getDetectedContentType() {
        return detectedContentType;
    }

    public long getSizeBytes() {
        return sizeBytes;
    }

    public String getSha256() {
        return sha256;
    }

    public Long getUploadedBy() {
        return uploadedBy;
    }

    public Instant getUploadedAt() {
        return uploadedAt;
    }
}
