package com.uptrail.model;

public enum MailTemplate {
    APPLICATION_SUBMITTED,
    APPLICATION_UPDATED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    APPLICATION_REASSIGNED,
    CLAIM_SUBMITTED,
    CLAIM_APPROVED,
    CLAIM_REJECTED,
    CLAIM_REIMBURSED
}
